question_data = [
    {"text": "A slug's blood is green.", "answer": "True"},
    {"text": "The loudest animal is the African Elephant.", "answer": "False"},
    {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
    {"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
    {"text": "In West Virginia, USA, if you accidentally hit an animal with your car, you are free to take it home to eat.", "answer": "True"},
    {"text": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.", "answer": "False"},
    {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
    {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
    {"text": "Google was originally called 'Backrub'.", "answer": "True"},
    {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
    {"text": "No piece of square dry paper can be folded in half more than 7 times.",
        "answer": "False"},
    {"text": "A few ounces of chocolate can to kill a small dog.", "answer": "True"},
    {"text": "The Great Wall of China is visible from space without the aid of binoculars or a telescope.", "answer": "True"},
    {"text": "The Great Wall of China is visible from space without the aid of binoculars or a telescope.", "answer": "True"},
    {"text": "The sun rises in the west.", "answer": "False"},
    {"text": "Water boils at 100 degrees Celsius at sea level.", "answer": "True"},
    {"text": "A year has 365 days.", "answer": "False"},
    {"text": "Elephants can fly.", "answer": "False"},
    {"text": "Python is a compiled language.", "answer": "False"},
    {"text": "The capital of France is Paris.", "answer": "True"},
    {"text": "The moon is made of cheese.", "answer": "False"},
    {"text": "Oxygen is a noble gas.", "answer": "False"},
    {"text": "Mount Kilimanjaro is the tallest mountain in the world.", "answer": "False"},
    {"text": "The Great Wall of China is visible from space.", "answer": "True"},
    {"text": "The Earth is flat.", "answer": "False"},
    {"text": "The Python programming language was named after the snake.", "answer": "True"},
    {"text": "A triangle has four sides.", "answer": "False"},
    {"text": "The Pacific Ocean is the largest ocean on Earth.", "answer": "True"},
    {"text": "Cats are mammals.", "answer": "True"},
    {"text": "The square root of 16 is 5.", "answer": "False"},
    {"text": "A leap year has 365 days.", "answer": "False"},
    {"text": "Diamonds are made of carbon.", "answer": "True"},
    {"text": "The capital of Japan is Tokyo.", "answer": "True"}
]
